### PR TITLE
Updates README.md with which strand contains information

### LINKED ISSUE #48: Help understanding what methyldackel is doing with this bam file
I’m eyeballing the methylation calls from methyldackel (Version: 0.3.0 (using HTSlib version 1.2.1) ) on my bam file ([bisulfite_test_bwameth.bam.zip](https://github.com/dpryan79/MethylDackel/files/1128462/bisulfite_test_bwameth.bam.zip)).
When I count “by eye” in IGV or samtools tview(below), I find 12 A and 49 G for one specific position (I:21312) in Neuorspora crassa.

Methyldackel produces counts of 11 methylated and 5 unmethylated
I	21311	21312	68	11	5

I thought maybe this was due to me counting both reads by eye, but I tried to avoid doing that (and the difference is too big anyway).

I also tried with some crazy options to see if things were being filtered that I didn’t appreciate:
MethylDackel  extract -D 200000 -F 0 -p 1 -q 0  --keepDupes --keepDiscordant /mnt/galaxy/data/genome/nc12/sam_indexes/nc12/nc12.fa test.bam
I	21311	21312	57	20	15
still not enough reads being considered...

Tweaking IGV to flag reads with mapq < 5  yields 9 A and 28 G in the histogram… still way different from methyldackel...

Can you help me understand what's going on?

here's the samtools tview  output in the relevant location:
```
21311
CGAT
.R..
.A..
.A..
....
....
.A..
....
A...
....
....
....
T...
....
....
.A..
....
....
.A..
....
....
....
.A..
,,,,
....
....
t,,,
....
....
.A..
,,,,
,,,,
.A..
....
....
T...
.A..
.A..
T...
....
....
....
....
....
....
T...
....
,,,,
,,,,
.A..
,a,,
,,,,
....
....
,a,,
,,,,
T...
....
,a,,
....
....
....
....
....
....
.A..
....
....
....
—
```

### PR DESCRIPTION
**Pull request by bwlang**
I was confused (fixes #48) about how to manually tabulate methylation calls.  maybe this will help others who are new to methylation analysis.  I also considered putting this in the ignored alignments section, but I think this intro is a better spot.

### CODE REVIEW

**Comment by dpryan79** [comment]
This isn't correct; read #2 does contain methylation information, though possibly not for the strand one would naively think. This isn't any different than SNP calling, where paired-end reads are only telling you directly about one strand, regardless of their orientation, since a single strand is what forms the cluster.

**Comment by bwlang** [comment]
Hmm maybe I'm still missing something... a snp calling experiment is not directional like a bisulfite exp right? So this is not about r1 vs r2, but  about half the inserts containing information about a given position.  Maybe first in pair and second in pair is not right... maybe it should read original top vs original bottom?

**Comment by dpryan79** [comment]
People normally assume that strands are complementary, which is generally true for SNPs, though I assume there's some exception out there for which people do similarly stranded library-prep. But yes, the issue is mostly original top vs. original bottom strand and each pair only being informative for one of those. The weird strandedness stuff is the most confusing part of BSseq.

**Comment by bwlang** [comment]
I think this is no longer relevant...

**Pull request closed without merging**
